name: lab4
on: push
jobs:
  gcc:
    runs-on: ubuntu-latest
    steps:
          - name: get the repository code
            uses: actions/checkout@v3
          - run: sudo apt update -y
          - run: sudo apt install cmake
          - run: cd hello_world_application && cmake . -B _build && cd _build && make
          - run: cd solver_application && cmake . -B _build && cd _build && make

  clang:
     runs-on: ubuntu-latest
     steps:
           - name: get the repository code
             uses: actions/checkout@v3
           -  run: sudo apt update -y
           - run: sudo apt install cmake
           - run: sudo apt install clang
           - run: cd hello_world_application && cmake . -B _build -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang && cd _build && make
           - run: cd solver_application && cmake . -B _build -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang && cd _build && make
